server:
  port: 8080

# jpa query log
decorator:
  datasource:
    p6spy:
      logging: slf4j
      enable-logging: false

spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /cms-db-console
      settings:
        web-allow-others: true
  datasource:
    hikari:
      connection-timeout: 1000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update