server:
  port: 8080

springdoc:
  swagger-ui:
    path: '/clan/cms/docs/apis'

# jpa query log
decorator:
  datasource:
    p6spy:
      logging: slf4j
      enable-logging: true

spring:
  application:
    name: coc
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 10MB
  jackson:
    default-property-inclusion: non_null
  h2:
    console:
      enabled: true
      path: /cms-db-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/database/h2
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 1000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

external:
  coc:
    api-key: ${COC_API_KEY}
    domain: https://api.clashofclans.com
    timeout:
      connect: 1s
      response: 1s
      read: 2s
      write: 2s
    end-point:
      clans:
        prefix: /v1/clans
        clan-tag: /{clanTag}
        capital-raid-seasons: /{clanTag}/capitalraidseasons
        current-war: /{clanTag}/currentwar
        league-group: /{clanTag}/currentwar/leaguegroup
        members: /{clanTag}/members
      players:
        prefix: /v1/players
        player: /{playerTag}
      leagues:
        prefix: /v1
        leagues: /leagues
      leaguetier:
        prefix: /v1
        league-tier: /leaguetiers
      clanwarleagues:
        prefix: /v1/clanwarleagues/wars
        round-tag: /{roundTag}
        war-tag: /{warTag}

# circuit-breaker 설정
resilience4j:
  circuitbreaker:
    instances:
      clashOfClanApi:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3

# CMS 어드민 계정 설정
cms:
  admin-id: ${ADMIN_ID}
  admin-password: ${ADMIN_PASSWORD}

# 스케쥴링 활성화 여부
scheduling:
  enabled: false
  collect:
    clan-war:
      ended-sec: 60 # 클랜전 종료 수집
      current: "0 */15 * * * *" # 클랜전 수집
    capital:
      ended: "0 0/5 16 ? * MON" # 캐피탈 종료
    event:
      team-legend:
        enabled: false
        min-record-milli-sec: 60000 # 팀 전설내기 분 단위 기록, 1분 (60 * 1000)
        daily-record: "0 59 13 ? * *" # 팀 전설내기 일별 기록
    player:
      sync:
        delay: 5000 # 서버 구동 후 실행 대기 (초)
        milli-sec: 300000 # 동기화 시간 5분 (5 * 60 * 1000)
      legend:
        enabled: false
        record-milli-sec: 60000 # 플레이어 기록, 10초 (10 * 1000) -> 전설 계정 수집
  reset:
    season: "0 1 14 ? * MON" # 시즌 초기화

# 명예의전당 랭킹 표기 설정값
hall-of-fame:
  ranking: 15
  average: 3

file:
  upload-path: ./web
