server:
  port: 8080
  # 1core server
  tomcat:
    threads:
      max: 150
      min-spare: 5
    accept-count: 30

# jpa query log
decorator:
  datasource:
    p6spy:
      logging: slf4j
      enable-logging: false

spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /cms-db-console
      settings:
        web-allow-others: true
  datasource:
    hikari:
      minimum-idle: 3       # 최소 유지 커넥션 개수
      maximum-pool-size: 10  # 최대 커넥션 개수
      idle-timeout: 60000    # 60초 동안 사용되지 않으면 해제
      connection-timeout: 3000 # 커넥션 요청이 3초를 초과하면 예외 발생
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

scheduling:
  enabled: true